---

- name: Ensure all packages are up to date
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Install required packages
  become: true
  ansible.builtin.apt:
    name:
      - xfsprogs
    state: present

# sudo modprobe -v xfs

# fdisk -l 
# Disk /dev/xvda: 40 GiB, 42949672960 bytes, 83886080 sectors
# Disk /dev/xvdf: 400 GiB, 429496729600 bytes, 838860800 sectors

# mkfs.xfs [options] /dev/device 
