---
- name: Install roles and collections
  when: ansible_connection == 'local'
  community.general.ansible_galaxy_install:
    type: both
    requirements_file: ./collections/requirements.yml

- name: Write gathered facts to a file
  ansible.builtin.copy:
    content: "{{ ansible_facts | to_nice_json }}"
    dest: "/tmp/ansible_facts_{{ inventory_hostname }}.json"

- name: Packages
  ansible.builtin.import_tasks: packages/main.yml
  tags:
    - packages

- name: Docker
  ansible.builtin.import_tasks: docker/main.yml
  tags:
    - docker

- name: Configuration
  ansible.builtin.import_tasks: configuration/main.yml
  tags:
    - configure

- name: Security
  ansible.builtin.import_tasks: security/main.yml
  tags:
    - security
