---
- name: Install roles and collections
  when: ansible_connection == 'local'
  community.general.ansible_galaxy_install:
    type: both
    requirements_file: ./collections/requirements.yml

- name: Write gathered facts to a file
  ansible.builtin.copy:
    mode: "0644"
    content: "{{ ansible_facts | to_nice_json }}"
    dest: "/tmp/ansible_facts_{{ inventory_hostname }}.json"

- name: Disk Configuration
  when: ubtu22_run_task_disk
  ansible.builtin.import_tasks: packages/main.yml
  tags:
    - packages

- name: Packages
  when: ubtu22_run_task_packages
  ansible.builtin.import_tasks: packages/main.yml
  tags:
    - packages

- name: Docker
  when: ubtu22_run_task_docker
  ansible.builtin.import_tasks: docker/main.yml
  tags:
    - docker

- name: Configuration
  when: ubtu22_run_task_configuration
  ansible.builtin.import_tasks: configuration/main.yml
  tags:
    - configure

- name: Security
  when: ubtu22_run_task_security
  ansible.builtin.import_tasks: security/main.yml
  tags:
    - security
