---

- name: Set the machine FQDN
  when: ansible_fqdn is defined and ansible_fqdn | length <= 32
  become: true
  ansible.builtin.hostname:
    name: "{{ ansible_fqdn }}"

- name: Set timezone to Europe/Amsterdam
  become: true
  community.general.timezone:
    name: Europe/Amsterdam

- name: Restart the systemd-timedated service
  become: true
  ansible.builtin.service:
    name: systemd-timedated
    state: restarted

- name: Enable unattended upgrades
  become: true
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    mode: "0644"
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";

- name: Create ~/.ssh if not exist
  ansible.builtin.file:
    path: /home/{{ ansible_user_id }}/.ssh
    owner: "{{ ansible_user_id }}"
    state: directory
    mode: "0700"

- name: Check if SSH private key already exists
  ansible.builtin.stat:
    path: /home/{{ ansible_user_id }}/.ssh/id_rsa
  register: file_private_key

- name: Generate SSH private and public keys
  when: not file_private_key.stat.exists
  community.crypto.openssh_keypair:
    path: /home/{{ ansible_user_id }}/.ssh/id_rsa
    type: ed25519
    owner: "{{ ansible_user_id }}"
    mode: '0600'
  register: ssh_keypair

- name: Add SSH public key to authorized_keys
  when: not file_private_key.stat.exists
  ansible.posix.authorized_key:
    user: "{{ ansible_user_id }}"
    key: "{{ ssh_keypair.public_key }}"

- name: Disable SSH password authentication
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: present

- name: Enable SSH key-based login
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PubkeyAuthentication'
    line: 'PubkeyAuthentication yes'
    state: present

- name: Restart SSH service
  when:
    - not file_private_key.stat.exists
    - ssh_keypair.stat.exists
  become: true
  ansible.builtin.service:
    name: ssh
    state: restarted

#    - name: Configure additional partition as xfs
#      filesystem:
#        fstype: xfs
#        dev: /dev/sdb1  # Replace with your actual partition

 #   - name: Mount the partition to /mnt/disk2
 #     mount:
 #       path: /mnt/disk2
 #       src: /dev/sdb1
 #       fstype: xfs
 #       state: mounted

#    - name: Symlink ~/.local/share/docker to /mnt/disk2/data/docker
#      file:
#        src: /mnt/disk2/data/docker
#        dest: /home/{{ ansible_user_id }}/.local/share/docker
#        state: link
