---

- name: Set the machine FQDN
  when: ansible_fqdn is defined and ansible_fqdn | length <= 32
  become: true
  ansible.builtin.hostname:
    name: "{{ ansible_facts['fqdn'] }}"

- name: Set timezone to Europe/Amsterdam
  become: true
  community.general.timezone:
    name: Europe/Amsterdam

- name: Restart the systemd-timedated service
  become: true
  ansible.builtin.service:
    name: systemd-timedated
    state: restarted

- name: Enable unattended upgrades
  become: true
  ansible.builtin.copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    mode: "0644"
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";

- name: Create ~/.ssh if not exist
  ansible.builtin.file:
    path: /home/{{ ansible_facts['user_id'] }}/.ssh
    owner: "{{ ansible_facts['user_id'] }}"
    state: directory
    mode: "0700"

- name: Check if SSH private key already exists
  ansible.builtin.find:
    paths: "/home/{{ ansible_facts.user_id }}/.ssh"
    file_type: file
    patterns:
      - "id_*"
      - "*.key"
    excludes:
      - "*.pub"
      - "known_hosts"
      - "authorized_keys"
      - "config"
  register: file_private_key
  failed_when: false

- name: Generate SSH private and public keys
  when: file_private_key.matched == 0
  community.crypto.openssh_keypair:
    path: /home/{{ ansible_facts['user_id'] }}/.ssh/id_rsa
    type: ed25519
    owner: "{{ ansible_facts['user_id'] }}"
    mode: '0600'

- name: Get public key
  ansible.builtin.find:
    paths: "/home/{{ ansible_facts.user_id }}/.ssh"
    file_type: file
    patterns:
      - "*.pub"
    excludes:
      - "id_*"
      - "*.key"
      - "known_hosts"
      - "authorized_keys"
      - "config"
  register: ssh_keypair
  failed_when: false

- name: Add SSH public key to authorized_keys
  when: ssh_keypair is succeeded
  ansible.posix.authorized_key:
    user: "{{ ansible_facts['user_id'] }}"
    key: "{{ ssh_keypair.public_key }}"

- name: Disable SSH password authentication
  when: ssh_keypair.public_key is defined
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: present

- name: Enable SSH key-based login
  when: ssh_keypair.public_key is defined
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PubkeyAuthentication'
    line: 'PubkeyAuthentication yes'
    state: present

- name: Restart SSH service
  when:
    - ssh_keypair.public_key is defined
  become: true
  ansible.builtin.service:
    name: ssh
    state: restarted

#    - name: Configure additional partition as xfs
#      filesystem:
#        fstype: xfs
#        dev: /dev/sdb1  # Replace with your actual partition

 #   - name: Mount the partition to /mnt/disk2
 #     mount:
 #       path: /mnt/disk2
 #       src: /dev/sdb1
 #       fstype: xfs
 #       state: mounted

#    - name: Symlink ~/.local/share/docker to /mnt/disk2/data/docker
#      file:
#        src: /mnt/disk2/data/docker
#        dest: /home/{{ ansible_user_id }}/.local/share/docker
#        state: link
