---
- name: Set Microsoft repo variables (Debian / Ubuntu only)
  when: 
    - ansible_facts['architecture'] == "amd64"
    - pkg_pwsh
  register: msprod_repo_var
  ansible.builtin.set_fact:
    ms_base: "https://packages.microsoft.com/config"
    ms_deb: "packages-microsoft-prod.deb"
    ms_repo_path: >-
      {% if ansible_facts.distribution == "Debian" %}
      debian/{{ ansible_facts.distribution_major_version }}
      {% elif ansible_facts.distribution == "Ubuntu" %}
      ubuntu/{{ ansible_facts.distribution_version }}
      {% else %}
      unsupported
      {% endif %}

- name: Download Microsoft repository package
  when: 
    - pkg_pwsh
    - msprod_repo_var is succeeded
  register: msprod
  ansible.builtin.get_url:
    url: "{{ ms_base }}/{{ ms_repo_path }}/{{ ms_deb }}"
    dest: "/tmp/{{ ms_deb }}"
    mode: "0644"
    force: true

- name: Install Microsoft repository package
  become: true
  register: msprod_repo
  when: 
    - pkg_pwsh
    - msprod is succeeded
  ansible.builtin.apt:
    deb: "/tmp/{{ ms_deb }}"

# - name: Add Microsoft APT repository
#  when: msprod.stat.exists
#  become: true
#  ansible.builtin.apt_repository:
#    repo: "deb https://packages.microsoft.com/ubuntu/{{ ansible_distribution_version }}/prod {{ ansible_distribution_release }} main"
#    state: present

- name: Download Webmin Repo Setup
  register: webmin_repo_download
  ignore_errors: true
  when:
    - pkg_webmin
    - ansible_facts['architecture'] == "amd64"
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/webmin/webmin/master/setup-repos.sh
    dest: /tmp/setup-repos.sh
    mode: '0740'

- name: Configure Webmin Repo
  register: configure_webmin
  when:
    - pkg_webmin
    - webmin_repo_download is succeeded
  become: true
  args:
    creates: /etc/apt/sources.list.d/webmin.list
  ansible.builtin.shell: |
    sh /tmp/setup-repos.sh -f

- name: Ensure all packages are up to date
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Install required packages
  become: true
  ansible.builtin.apt:
    name:
      - ufw
      - ethtool
      - htop
      - screen
      - nano
      - net-tools
      - dnsutils
      - openssl
      - build-essential
      - p7zip-full
      - curl
      - gnupg
      - apt-transport-https
      - ca-certificates
      - libssl-dev
      - openssh-server
      - uidmap
      - dbus-user-session
      - unattended-upgrades
      - pkg-config
    state: present

- name: Install PWSH
  when:
    - ansible_facts['architecture'] == "amd64"
    - msprod_repo is succeeded
    - pkg_pwsh
  become: true
  ansible.builtin.apt:
    name:
      - powershell
    state: present

- name: Install Webmin
  when:
    - configure_webmin is succeeded
  become: true
  ansible.builtin.apt:
    name:
      - webmin
    state: present

- name: Install hardware packages
  when:
    - not vm
  become: true
  ansible.builtin.apt:
    name:
      - lshw
      - hw-probe
    state: present

- name: Install SNMP
  when:
    - pkg_snmp
  become: true
  ansible.builtin.apt:
    name:
      - snmpd
      - snmp-mibs-downloader
    state: present
