---

- name: Download the Microsoft repository key file
  ansible.builtin.get_url:
    url: "https://packages.microsoft.com/config/{{ ansible_facts['distribution'] }}/{{ {{ ansible_facts['distribution_major_version']  }} }}/packages-microsoft-prod.deb"
    dest: "/tmp/packages-microsoft-prod.deb"
    mode: "0644"

- name: Task name
  ansible.builtin.stat:
    path: "/tmp/packages-microsoft-prod.deb"
  register: msprod

- name: Register the Microsoft repository key
  become: true
  when: msprod.stat.exists
  ansible.builtin.apt:
    deb: "/tmp/packages-microsoft-prod.deb"

- name: Remove the Microsoft repository key file
  when: msprod.stat.exists
  ansible.builtin.file:
    path: "/tmp/packages-microsoft-prod.deb"
    state: absent

# - name: Add Microsoft APT repository
#  when: msprod.stat.exists
#  become: true
#  ansible.builtin.apt_repository:
#    repo: "deb https://packages.microsoft.com/ubuntu/{{ ansible_distribution_version }}/prod {{ ansible_distribution_release }} main"
#    state: present

- name: Download Webmin Repo Setup
  register: webmin_repo_download
  ignore_errors: true
  when:
    - pkg_webmin
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/webmin/webmin/master/setup-repos.sh
    dest: /tmp/setup-repos.sh
    mode: '0740'

- name: Configure Webmin Repo
  when:
    - pkg_webmin
    - webmin_repo_download.state == "file"
  become: true
  args:
    creates: /etc/apt/sources.list.d/webmin.list
  ansible.builtin.shell: |
    sh /tmp/setup-repos.sh -f

- name: Ensure all packages are up to date
  become: true
  ansible.builtin.apt:
    update_cache: true

- name: Install required packages
  become: true
  ansible.builtin.apt:
    name:
      - ufw
      - ethtool
      - htop
      - screen
      - nano
      - net-tools
      - dnsutils
      - openssl
      - build-essential
      - p7zip-full
      - curl
      - gnupg
      - apt-transport-https
      - ca-certificates
      - libssl-dev
      - software-properties-common
      - openssh-server
      - uidmap
      - dbus-user-session
      - unattended-upgrades
      - pkg-config
      - powershell
      - tripwire
    state: present

- name: Install PWSH
  when: msprod.stat.exists
  become: true
  ansible.builtin.apt:
    name:
      - powershell
    state: present

- name: Install Webmin
  when:
    - pkg_webmin
  become: true
  ansible.builtin.apt:
    name:
      - webmin
    state: present

- name: Install hardware packages
  when:
    - not vm
  become: true
  ansible.builtin.apt:
    name:
      - lshw
      - hw-probe
    state: present

- name: Install SNMP
  when:
    - pkg_snmp
  become: true
  ansible.builtin.apt:
    name:
      - snmpd
      - snmp-mibs-downloader
    state: present
